### ISSUE TITLE
Criar comando de login no backend

### ISSUE THREAD

**Issue by robertoconceicao** [robertoconceicao/bobcats#1]
Criar comando de login no backend.
serão passados para o backend: 
delogin e desenha tudo minúsculo
na resposta retorna tbem os dados do usuário caso seja sucesso.

**Comment by oselame** [comment]
Feito, incluido
"Usuariologin": {
    "PUT  /api/usuariologin": "Valida Usuario cadastrado"
  }
ex:
{ delogin: "XXX", desenha: "YYYY" }

**Comment by robertoconceicao** [comment]
Ok esta funcionando.
